# Generated by Django 5.2.1 on 2025-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=100, unique=True)),
                ('destination_sum', models.IntegerField()),
                ('weight_planet', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
