# Generated by Django 5.2.1 on 2025-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetinfos',
            name='destination_sum',
            field=models.BigIntegerField(),
        ),
    ]
