# Generated by Django 5.2.1 on 2025-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_float', models.FloatField()),
                ('data_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
