# Generated by Django 5.2.1 on 2025-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calc', '0002_const'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacalc',
            name='planet_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
